#######################################
###       Logging Configuration     ###
#######################################
expt:
  project_name:     'metassl'
  session_name:     'development'
  experiment_name:  'default_config_1'
  job_name:         'local'
  expt_dir:         '/home/ferreira/workspace/experiments/metassl'
  save_model:       True                  # save the model to disc
  resume_training:  False                 # resumes training if model with same config exists
  resume_optimizer: False                 # resumes optimizer states if model with same config exists
  "ddp":            True,                 # use distributed data parallel


#######################################
###     Training Configuration      ###
#######################################
train:
  eval_freq:  100                         # every eval_freq iteration will the model be evaluated
  seed:       123                         # random seed of numpy and torch
  batch_size: 512
  epochs:     100                         # epochs to train
  gpus:       8                           # number of GPUs to train on


#######################################
###       Model Configuration       ###
#######################################
model:
  model_type: "resnet50"                  # supported models: all torchvision ResNets
  seed:       123


#######################################
###     Optimizer Configuration     ###
#######################################
optim:
  optimizer:        "sgd"                 # optimizer type, options: adam adamW rmsprop adabelief sgd
  schedule:         "cosine"              # learning rate schedule, options: 'noam' 'cosine' 'cosineW' 'plateau' 'step' 'const' 'cosineWarm' 'exponential' 'None' (BOHO case)
  warmup:           1000                  # 0 (turned off) or higher (e.g. 1000 ~ 5 epochs at batch size 256 on CIFAR100)
  factor:           1.0                   # noam factor
  weight_decay:     0.0001

  lr_low:           0.0                   # the minimum LR (eta_min) for schedulers 'cosine', 'cosineWarm' and 'plateau'
  lr_high:          0.1                   # the default LR for all schedulers, in case of const LR schedule: set lr_high=lr_low
  clip_grad:        False                 # gradient cliping, options: 0.1 ... 100, False
  scheduler_epochs: 100                   # T_max or T_0 in 'cosine' and 'cosineWarm' scheduler, in case of 'step' scheduler this denotes when scheduler should step


#######################################
###       Data Configuration        ###
#######################################
data:
  seed:     123
  dataset:  'ImageNet'                    # supported datasets: CIFAR10, CIFAR100, ImageNet
  data_dir: '/home/ferreira/workspace/data/metassl'


